LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := Alibi
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := app-arm64-v8a-release.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED

# TODO: remove 
# TODO Remove and add LOCAL_OPTIONAL_USES_LIBRARIES per apk
# PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true
LOCAL_OPTIONAL_USES_LIBRARIES := androidx.camera.extensions.impl

include $(BUILD_PREBUILT)