LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := Files
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := MiXplorer_v6.71.10_B26080710.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OPTIONAL_USES_LIBRARIES := com.sec.android.app.multiwindow

# trial not flashing it
LOCAL_PRODUCT_MODULE := true
LOCAL_MULTILIB := 64

# Unconfirmed so far
LOCAL_UNCOMPRESS_DEX := false
LOCAL_DEX_PREOPT := false

# TODO: remove and properly define LOCAL_OPTIONAL_USES_LIBRARIES instead
LOCAL_ENFORCE_USES_LIBRARIES := false

include $(BUILD_PREBUILT)
