LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := KernelSU
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := KernelSU_Next_v3.3.0_33214-release.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED

# trial not flashing it
LOCAL_PRODUCT_MODULE := true
LOCAL_MULTILIB := 64

# Unconfirmed so far
LOCAL_UNCOMPRESS_DEX := false
LOCAL_DEX_PREOPT := false
# TODO: remove and properly define LOCAL_OPTIONAL_USES_LIBRARIES instead
LOCAL_ENFORCE_USES_LIBRARIES := false

include $(BUILD_PREBUILT)
