LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := Parannoying
LOCAL_SRC_FILES := app-prod-release.apk

LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/$(LOCAL_SRC_FILES)

LOCAL_PRODUCT_MODULE := true

LOCAL_UNCOMPRESS_DEX := false
LOCAL_DEX_PREOPT := false

LOCAL_ENFORCE_USES_LIBRARIES := false

include $(BUILD_PREBUILT)